NewBoston/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/',include('music.urls')),
    path('rest/',include('restapi.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
   

music/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
app_name='music'
urlpatterns = [
    #path('',views.index,name='index'),
    url(r'^$',views.IndexView.as_view() ,name='index'),
    url(r'^register/$',views.UserFormView.as_view(),name='register'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='details'),
    url(r'album/add/$',views.Album_create.as_view(),name='album_add'),
    url(r'album/add_song/$',views.Song_add.as_view(),name='add_song'),
    url(r'album/(?P<pk>[0-9]+)/$',views.Album_update.as_view(),name='album_update'),
    url(r'album/(?P<pk>[0-9]+)/delete/$',views.Album_delete.as_view(),name='album_delete'),
    url(r'album/(?P<pk>[0-9]+)/delete_song',views.Song_delete.as_view(),name='song_delete'),
    url(r'/lyrics/$',views.Show_lyrics,name='lyrics'),
    url(r'^music/make_album_fav',views.make_album_fav,name='album_fav'),
    #url(r'^(?P<album_id>[0-9]+)/fav/$',views.fav,name='fav'),
]

 

restapi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
urlpatterns = [
    url(r'^$',views.index.as_view(),name='index'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

music/models.py
from django.db import models
from django.urls import reverse
from django.shortcuts import  redirect

# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length=20)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)
    
    def get_absolute_url(self):
        return reverse('music:details',kwargs={'pk':self.pk})
    def __str__(self):
        return self.album_title

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)#if we delete album then songs will also will be deleted.
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_fav = models.BooleanField(default=False)
    def __str__(self):
        return self.song_title
    def get_absolute_url(self):
        return reverse('music:details',kwargs={'pk':self.album.id})

restapi/models.py
from django.db import models
from music.models import Album

# Create your models here.

music/forms.py
from django.contrib.auth.models import  User
from django import  forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','email','password']

music/views.py
from django.http import request,Http404
from django.http.response import JsonResponse
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from django.template import context
from .models import Album, Song
from django.template import loader
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.shortcuts import render,redirect
from django.contrib.auth import login,authenticate,logout
from django.views.generic import View
from .forms import UserForm
import lyricsgenius as lg
class IndexView(generic.ListView):
    template_name='music/index.html'
    context_object_name = 'all_album'
    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'

class Album_create(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class Album_update(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

class Album_delete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name,{'form':form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            
            #returns user object if credentials are corrects
            user = authenticate(username=username,password=password)
            if user is not None:
                if user.is_active:
                    login(request,user) #login step
                    return redirect('music:index')
        return render(request, self.template_name,{'form':form})

class Song_add(CreateView):
    model = Song
    fields = ['album','file_type','song_title']
class Song_delete(DeleteView):
    model = Song
    success_url = reverse_lazy('music:details')
def make_album_fav(request):
    id = request.GET['id']
    a1 = Album.objects.get(id=id)
    a1.is_favorite = True
    a1.save()
    return JsonResponse({'fav':'Favorite'})

def Show_lyrics(request):
    genius = lg.Genius('4x-nTc-nUzekdFO6SyL2U_IJ93xxvTtztp_ox4hfqOBoEnZolVv6jEDMvj_F0M_B',skip_non_songs=True, excluded_terms=["(Remix)", "(Live)"], remove_section_headers=True)
    artist = genius.search_artist(request.POST['artist'], max_songs=0, sort="title")
    song = genius.search_song(request.POST['id'])
    s1 = song.lyrics
    s1 = list(s1.split('\n'))
    return render(request,'music/lyrics.html',{'context':s1})


# Create your views here.
"""
def index(request):
    #return HttpResponse("<h1>HomePage</h1>")#you can enter plane text too.
    html = ''
    all_album = Album.objects.all()
    template = loader.get_template('music/index.html')
    context = {
        'all_album':all_album
    }
    for album in all_album:
        url = str(album.id)+'/'
        html += '<a href="'+url+'">'+album.album_title+'</a><br>'
    return HttpResponse(html)
    #return HttpResponse(template.render(context,request))
    return render(request,'music/index.html',context)
def details(request,album_id):
    album = get_object_or_404(Album,id=album_id)
    try:
        album = Album.objects.get(pk=album_id)
    except Album.DoesNotExist:
        raise Http404("Album does not exsits")
    return render(request,'music/detail.html',{'album':album})

def fav(request,album_id):
    album = get_object_or_404(Album,id=album_id)
    try:
        song = album.song_set.get(id=request.POST['song'])
    except (KeyError,Song.DoesNotExist):
        return render(request,'music/detail.html',{
            'album':album,
            'error_message':"You did not select valid song!!"
        })
    else:
        song.is_fav = True
        song.save()
        return render(request,'music/detail.html',{'album':album})
"""

restapi/views.py
from django.shortcuts import render
from music.models import Album
from rest_framework.views import APIView
from .serializers import AlbumSerializer
from rest_framework.response import Response
from rest_framework import  status
# Create your views here.

class index(APIView):
    def get(self,request):
        albums = Album.objects.all()
        serial = AlbumSerializer(albums,many=True)
        return Response(serial.data)
    def post(self,request):
        pass

music/templates/music/album_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Album{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}    
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>{% block title %}Home{% endblock %}</title>   
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- logo -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topnavbar">
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Home</a>
            </div> 
            <div class="collapse navbar-collapse" id="topnavbar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
                            
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                        <div class="form-group">
                            <input type="text" class="form-control" name="q" value="">
                        </div>
                        <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        {% block icon %}
                        <a href="{% url 'music:album_add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                        </a>
                        {% endblock %}
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                        </a>
                    </li>
                </ul>
            </div>
    
        </div>    
    </nav>
    {% block body %}
    {% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Songs{% endblock %}
{% block icon %}
<a href="{% url 'music:add_song' %}">
<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Song
</a>
{% endblock %}
{% block body %}
<img src="{{ album.album_logo.url }}" alt="Logo" />
<h1>{{album}}</h1>
<h2>{{album.artist}}</h2>
{% for song in album.song_set.all %}
<br>
<h4 style="display: inline;">{{ song.song_title }}</h4>
<a href="{% url 'music:song_delete' song.id %}" class="btn btn-primary btn-sm" role="button" style="display: inline;">
    <span class="glyphicon glyphicon-trash" style="display: inline;"></span>
</a>
    <form action="{% url 'music:lyrics'%}" method="POST" >
    {% csrf_token %}
    <input type='hidden' name='id' value="{{ song.song_title }}" />
    <input type='hidden' name='album_id' value="{{ album.id }}" />
    <input type='hidden' name='artist' value="{{ album.artist }}" />
    <button type="submit">
    <span class="glyphicon glyphicon-plus" aria-hidden="true" style="margin:5px"></span>Lyrics
</button>
</form>
    
<br>
{% endfor %}
{% endblock %}
<!--
<form action="{% url 'music:fav' album.id %}" method="POST">
{% csrf_token %}
{% for song in album.song_set.all %}
<input type='radio' id="song{{ forloop.counter }}" name='song' value="{{song.id}}">
<label for="song{{ forloop.counter }}">{{ song.song_title }}
{% if song.is_fav %}
<img src="http://i.imgur.com/b9b13Rd.png" />
{% endif %}
</label><br>
{% endfor %}
<input type='submit'>
</form>
-->

music/templates/music/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.error }}</span>
        </div> 
        <label class="control-label col-sm-2">{{ field.label_tag }}</label> 
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %} {% block title %}Album{% endblock %} 
{% block body %} 
{% if all_album %}
<div class="row">
  {% for album in all_album %}
  <div class="col-md-3">
    <div class="border border-primary">
      <div class="card mb-4 shadow-sm">
        <img src="{{ album.album_logo.url }}" alt="Logo" />
      </div>
      <div class="card-body">
        <h3 class="card-text">{{album.album_title}}</h3>
        <div class="d-flex justify-center-between align-items-center">
          <a
            href="{% url 'music:details' album.id %}"
            class="btn btn-primary btn-sm"
            role="button"
            >View Details</a
          >
          {% if album.is_favorite %}
          <span class="glyphicon glyphicon-heart" id='like{{ forloop.counter }}'></span>
          {% else %}
          <span class="glyphicon glyphicon-heart-empty" id='like{{ forloop.counter }}'></span>
          {% endif %}
          <!--Delete-->
          
          <script>
              $("#like{{forloop.counter}}").click(function(e){
                  e.preventDefault();
                  var xhr = new XMLHttpRequest();
                  var id = "{{ album.id }}";
                  xhr.open('GET','music/make_album_fav?id='+id,true);
                  xhr.onload = function() {
                      var lable = JSON.parse(xhr.responseText);
                      document.getElementById('like{{forloop.counter}}').classList.remove("glyphicon-heart-empty");
                      document.getElementById('like{{forloop.counter}}').classList.add("glyphicon-heart");
                  }
                  xhr.send();
                })
          </script>
          <a
            href="{% url 'music:album_delete' album.id %}"
            class="btn btn-primary btn-sm"
            role="button"
          >
            <span class="glyphicon glyphicon-trash"></span>
          </a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% else %}
<h3>You have no Album</h3>
{% endif %} 
{% endblock %}

music/templates/music/lyrics.html
{% for i in context %}
<h4>{{ i }}</h4>
{% endfor %}

music/templates/music/registration.html
{% extends 'music/base.html' %}
{% block title %}Register{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}    
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/song_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

music/templates/music/song_form.html
{% extends 'music/base.html' %}
{% block title %}Songs{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}    
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}